{"name": "Verify that the user is able to Edit Policy from Manual SWM successfully with web small dataset", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53521): Max retries exceeded with url: /session/6ad746fb8cbe76d541d78358a0d946aa/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2D02CE840>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 16, in after_step\n    allure.attach(context.driver.get_screenshot_as_png()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "description": "The objective of this test case is to ensure that the users can successfully Edit Policy from Manual SWM with web small dataset", "steps": [{"name": "Given The user is successfully logged in the yieldWerx web application", "status": "passed", "start": 1722607695012, "stop": 1722607707196}, {"name": "When Click \"SWM\" in the left menu bar", "status": "passed", "start": 1722607707197, "stop": 1722607707228}, {"name": "When Click \"Manual SWM\" and Manual SWM window will open", "status": "passed", "start": 1722607707228, "stop": 1722607708959}, {"name": "When Click and select Source Facility, the Source Work Center, Source Device, Source Test Program", "status": "passed", "start": 1722607708959, "stop": 1722607733095}, {"name": "When Select Source Lots (73631), Source Wafers (Probe Count = 1)", "status": "passed", "start": 1722607733095, "stop": 1722607733096}, {"name": "When Click and select Target Facility, Target Work Center, Target Device, Target Test Program", "status": "passed", "start": 1722607733096, "stop": 1722607747536}, {"name": "When Select Target Lots (73631), Target Wafers (Probe Count = 1), \"<Policies>\"", "status": "passed", "start": 1722607747536, "stop": 1722607747537}, {"name": "When Select \"Wafer Plotting Option\" from \"Calculated Wafer/Die Size Settings and Actual Wafer/Die Size Setting\"", "status": "passed", "start": 1722607747537, "stop": 1722607747590}, {"name": "When Click \"Generate Manual SWM\" button to generate Manual SWM Wafer", "status": "passed", "start": 1722607747590, "stop": 1722607750635}, {"name": "Then Manual SWM Wafer as Combine Bin Wafer Map with Wafer ID: MC will be generated and be shown", "status": "passed", "start": 1722607750635, "stop": 1722607769100}, {"name": "When Click \"Edit Policy\" button available top right side of window", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53521): Max retries exceeded with url: /session/6ad746fb8cbe76d541d78358a0d946aa/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2D02CE840>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 16, in after_step\n    allure.attach(context.driver.get_screenshot_as_png()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1722607769100, "stop": 1722607801723}, {"name": "When Create SWM Policy window will open and make changes in General, Input Data & Rule selection, Output Data Selection, and Manage exceptions tab that you want to modify", "status": "skipped", "start": 1722607801725, "stop": 1722607801725}, {"name": "When Click \"Save\" button and Save Change", "status": "skipped", "start": 1722607801725, "stop": 1722607801725}, {"name": "When After popup appears choose any option and click \"OK\" button to save the changes", "status": "skipped", "start": 1722607801725, "stop": 1722607801725}, {"name": "Then Verify that the policy with made changes will be saved and Manual SWM will refresh", "status": "skipped", "start": 1722607801725, "stop": 1722607801725}], "start": 1722607695010, "stop": 1722607801725, "uuid": "632dbf19-7082-47e4-bc4a-24de94058ccd", "historyId": "8fa5b1ff96566685d72f623f3bbbb8ac", "fullName": "SWM Policies: Verify that the user is able to Edit Policy from Manual SWM successfully with web small dataset", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "YWPD-TC-335"}, {"name": "tag", "value": "retry"}, {"name": "feature", "value": "SWM Policies"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}